/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JPanel;

/**
 *
 * @author Victus
 */
public class CategoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form CategoryPanel
     */
    public CategoryPanel(CardLayout cardLayout, JPanel carPanel, ByCategoryPanel bycategorypanel) {
        initComponents(cardLayout, carPanel, bycategorypanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents(CardLayout cardLayout, JPanel carPanel, ByCategoryPanel bycategorypanel) {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        jButton1.setText("GAMBAR FIRAUN");
        jButton1.addActionListener(e -> {
            bycategorypanel.setData("GAMBAR FIRAUN");
            bycategorypanel.addDataList(new ImageObj("/javaapplication6/p1.png", "Lorem"));
            cardLayout.show(carPanel, "BYCATEGORY");
        });
        add(jButton1);
        jButton1.setBounds(360, 40, 164, 90);

        jButton2.setText("ART BERAT");
        jButton2.addActionListener(e -> {
            bycategorypanel.setData("ART BERAT");
            cardLayout.show(carPanel, "BYCATEGORY");
        });
        add(jButton2);
        jButton2.setBounds(10, 40, 164, 90);

        jButton3.setText("LUKISAN ROOM");
        jButton3.addActionListener(e -> {
            bycategorypanel.setData("LUKISAN ROOM");
            cardLayout.show(carPanel, "BYCATEGORY");
        });
        add(jButton3);
        jButton3.setBounds(180, 40, 164, 90);

        jButton4.setText("RAJA SIAP");
        jButton4.addActionListener(e -> {
            bycategorypanel.setData("RAJA SIAP");
            cardLayout.show(carPanel, "BYCATEGORY");
        });
        add(jButton4);
        jButton4.setBounds(190, 140, 164, 90);

        jButton5.setText("MONALISA");
        jButton5.addActionListener(e -> {
            bycategorypanel.setData("MONALISA");
            cardLayout.show(carPanel, "BYCATEGORY");
        });
        add(jButton5);
        jButton5.setBounds(360, 140, 164, 90);

        jButton6.setText("SULTAN MELAKA");
        jButton6.addActionListener(e -> {
            bycategorypanel.setData("SULTAN MELAKA");
            cardLayout.show(carPanel, "BYCATEGORY");
        });
        add(jButton6);
        jButton6.setBounds(10, 140, 164, 90);

        jButton7.setText("BACK");
        add(jButton7);
        jButton7.setBounds(40, 270, 65, 25);

        jButton8.setText("All");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton8.addActionListener(e -> {
            cardLayout.show(carPanel, "GALLARY");
        });

        jButton7.addActionListener(e -> {
            cardLayout.show(carPanel, "GALLARY");
        });

        jButton9.setText("Category");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(526, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton8)
                                        .addComponent(jButton9))
                                .addGap(0, 5, Short.MAX_VALUE)));

        add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton9ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
